### ISSUE TITLE
Change required for AppCenter: Require mpv in meson

### ISSUE THREAD

**Issue by cassidyjames** [ranfdev/raddiu#3]
Throwing a dialog about unmet dependencies that aren't in the stock elementary OS install and directing users to the Terminal to install them is not a great user experience; instead, you should include any necessary dependencies in your Debian packaging to ensure they're automatically installed along with your app.

**Comment by ranfdev** [comment]
```Depends: ${misc:Depends}, ${shlibs:Depends}, mpv```
isn't this enough? (in debian/control)
mpv is not installed when running ninja, but it should still be installed when a user installs the deb package, as required by the dependencies listed above. I think...

**Comment by cassidyjames** [comment]
@ranfdev ah, I meant meson, not Debian. My bad! You should be able to add it to the dependencies here:

https://github.com/ranfdev/raddiu/blob/da50f200cef60677ed27655d7d19fea6a10f7165/meson.build#L28-L34

**Comment by ranfdev** [comment]
The dependencies listed there are libraries needed for the compilation. ```mpv``` is not a library (i am running the program as a subprocess during runtime), so it doesn't work.  

Meson can check if a program is installed by using [find_program](https://mesonbuild.com/Reference-manual.html#find_program) and stop the compilation if it doesn't find it. But still, mpv is needed only during runtime, so it doesn't seem correct to stop the compilation.
Using ```find_program``` would also probably cause errors on the CI, because mpv is not installed there.

Anyway, from what i understand, the end user shouldn't have any problem when installing the program from the AppCenter because mpv is listed as a dependency in the debian/control file.

**Comment by cassidyjames** [comment]
@ranfdev ah alright. If issues crop top in testing the built Debian packages I'll let you know, otherwise I'll close this.
